### PR TITLE
Add API version to requests

### PR DESCRIPTION
**Pull request by ltk**
per the new requirement for a `&v=YYYYMMDD` appended to all request query strings (see https://groups.google.com/forum/#!topic/foursquare-api/X60gF5Zi0k4)

This PR allows for the version to be set during instantiation of Foursquare::Base, or alternatively fall back to the default of sending today's date in `YYYMMDD` format.

### CODE REVIEW

**Comment by rnfein** [comment]
:thumbsup:

**Comment by jamesosb** [comment]
Cheers @ltk  for the patch. My gem has died due to the versioning change so I'm using your fork. Unfortunately i'm getting an Argument Error:

 `ArgumentError (wrong number of arguments (3 for 1)):
  app/controllers/application_controller.rb:14:in 'new'
  app/controllers/application_controller.rb:14:in 'foursquare'
  app/controllers/locations_controller.rb:28:in 'block in show'
  app/controllers/locations_controller.rb:26:in 'show'`

I'm guessing it's to do with my base:

 `@foursquare ||= Foursquare::Base.new(@client_id = "XXXX", @client_secret = "XXXXX", @api_version = "20140116")`

Any suggestions before I try a monkey patch?

**Comment by ltk** [comment]
@jamesosb try

``` ruby
@foursquare ||= Foursquare::Base.new(
  :client_id     => "XXXX",
  :client_secret => "XXXXX",
  :api_version   => "20140116"
)
```

**Comment by jamesosb** [comment]
Perfect! Should've seen that - long day. Thanks for the help!

**Pull request merged**
